### ISSUE TITLE
Programs using ocaml-9p dump bisect output

### ISSUE THREAD

**Issue by talex5** [djs55/ocaml-9p#6]
My test server creates files like `bisect0001.out` when run.

Maybe a compile-time flag is needed to control this?

**Comment by djs55** [comment]
Oops!

I need to revamp the coverage testing probably based on the work
@simonjbeaumont did for ocaml-pci.

On Fri, Oct 23, 2015 at 3:17 PM, Thomas Leonard <notifications@github.com>
wrote:

> My test server creates files like bisect0001.out when run.
>
> Maybe a compile-time flag is needed to control this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djs55/ocaml-9p/issues/6>.
>



-- 
Dave Scott

**Comment by simonjbeaumont** [comment]
Well if you take a look at the open pull req for ocaml-pci I've made it generic. 

If you wait until Monday I'll factor it out into a common library. I was going to add it to xenvm and message-switch. Would be nice to have a couple more repos using it. 

Plan will be like the travis-opam stuff: wget and execute. No token required for coveralls either. 

-- simonjbeaumont@gmail.com (via iPhone)

**Comment by simonjbeaumont** [comment]
Update... see https://github.com/simonjbeaumont/ocaml-pci/pull/18. It's merged now and working. https://github.com/simonjbeaumont/ocaml-travis-coveralls is open for business!

**Comment by djs55** [comment]
I believe @simonjbeaumont's coveralls patches have fixed this
